# Generated by Django 6.1.1 on 2026-10-01 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("high_level", "0002_rename_stcok_pointdevente_stock_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="machine",
            name="superfice",
        ),
        migrations.RemoveField(
            model_name="produit",
            name="operations",
        ),
        migrations.AddField(
            model_name="machine",
            name="lieu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="high_level.lieu",
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="superficie",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="pays",
            name="salaire_minimum",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stock",
            name="lieu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="high_level.lieu",
            ),
        ),
        migrations.AlterField(
            model_name="lieu",
            name="quantite_machines",
            field=models.ManyToManyField(blank=True, to="high_level.quantitemachine"),
        ),
        migrations.AlterField(
            model_name="operation",
            name="Operation_suivante",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="high_level.operation",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="heures_de_travail",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="operation",
            name="machine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="high_level.machine",
            ),
        ),
    ]
